default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: lint
        name: Ruff check
        entry: uv run ruff check --fix
        language: system
        stages: [pre-commit]
        types: [python]
      - id: format
        name: Ruff format
        entry: uv run ruff format
        language: system
        stages: [pre-commit]
        types: [python]
      - id: types
        name: Ty check
        entry: uv run ty check
        language: system
        stages: [pre-commit]
        types: [python]
      - id: unit-tests
        name: Run unit tests
        entry: uv run pytest -m unit
        language: system
        stages: [pre-commit]
        types: [python]
        pass_filenames: false
      - id: integration-tests
        name: Run integration tests
        entry: uv run pytest -m integration
        language: system
        stages: [pre-push]
        types: [python]
        pass_filenames: false
      - id: application-tests
        name: Run application tests
        entry: uv run pytest -m application
        language: system
        stages: [pre-push]
        types: [python]
        pass_filenames: false
